### ISSUE TITLE
`Header::data<T>()` seems to be able to return an unaligned pointer to a `T`

### ISSUE THREAD

**Issue by mccolljr** [Gankra/thin-vec#21]
I'm wondering if this is possible incorrect:
https://github.com/Gankra/thin-vec/blob/73c37a2b7b252244d57d32f485fc7f2888768b33/src/lib.rs#L271-L278

It seems to me that 
https://github.com/Gankra/thin-vec/blob/73c37a2b7b252244d57d32f485fc7f2888768b33/src/lib.rs#L272
would need to be
```rust
if padding > 0 && self.cap() == 0 {
```
since `len` could be 0 even if capacity has been allocated - I could be wrong here, or missing something; I was borrowing some code from this project to use for a data structure I'm working on (I needed some additional data in the header), and was getting a weird pointer when trying to write the first element

Then, in order to make sure `*mut T` is properly aligned,
It seems to me (or, my to my untrained eyes, at least) that 
https://github.com/Gankra/thin-vec/blob/73c37a2b7b252244d57d32f485fc7f2888768b33/src/lib.rs#L276
would need to be
```rust
ptr.offset((header_size+padding) as isize) as *mut T 
```

A quick example [on the rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f7c565eedf15171472ce02f0756b537d) seems to indicate that the returned `*mut T` isn't aligned properly when the `padding` value isn't considered.

I could be totally wrong, just wanted to ask here

**Comment by Gankra** [comment]
Your analysis appears to be entirely correct. All of this behaves fine for `padding == 0`, which is why we never noticed this. The `padding > 0` code is very poorly tested because:

A) the header is naturally pointer-aligned, and you can't normally get a type with greater alignment without special annotations
B) The primary user of this compiles with the gecko_ffi feature, which hard panics if `padding > 0`.

Since you've already spent a while inspecting this, would you be willing to submit a PR and a test that stresses the `padding > 0` case?

**Comment by mccolljr** [comment]
@Gankra thanks for confirming my understanding, sorry for the delay. I've opened #22

**Comment by Gankra** [comment]
Thanks a lot!!
